### ISSUE TITLE
Update Azure Mappings to ATT&CK v9

### ISSUE THREAD

**Issue by MarkDavidson** [center-for-threat-informed-defense/security-stack-mappings#142]
As a user, I want the Azure Mappings update to ATT&CK v9, so that I can map security controls to the latest version of ATT&CK.

Acceptance Criteria:

1. ATT&CK v9 Mappings are added to this repository

**Comment by jonz-secops** [comment]
this should be closed in lieu of a request to update to ATT&CK v11
